version: '3'
services:
  db: # this is a service name
    container_name: mysql_db # this is a container name
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: customers
      MYSQL_ROOT_PASSWORD: password

web:
  image: nginx:latest
  container_name: nginx
   restart: always
   ports:
   — “80:80”